
import './globals.css'
import { Inter } from 'next/font/google'
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title:"Angelo's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/76d4d94d08.js" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
