
import './globals.css'
import { Mulish } from 'next/font/google'
import Script from "next/script";
import Navbar from './components/Navbar';
import { Analytics } from "@vercel/analytics/react";

const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title:"Angelo's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/76d4d94d08.js" />
      <body className={mulish.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
